[programs.localnet]
anchor_escrow = "BCewpMyxBDeLsj5SyrCmgvrYoxesbHsGRFtZ5TqX14Z1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
